# Methods {#methods}

The core idea behind the _twinetverse_ is fairly simply. Data is often put into rectangular format (think rows and columns, i.e.:`data.frame`) simply because it is most easily stored, and probably because we are familiar with the CSV table. As a result we tend to picture data in that format, including tweets.

However, tweets, like other datasets, should perhaps not be thought of in such a manner. Forcing data into a continuous list-like rectangular format often narrows our perspective of the said dataset. Let's illustrate with the case at hand, tweets.

## Tweets

Tweets appears in your timeline vertically, one after the other which make you can already picture the rowwise operation, each tweet is a row and each variable (author, text, created date, etc.), in fact this is how [rtweet](http://rtweet.info/) retruns tweets (more on that later). 

The table (`data.frame`) is a truly great invention, everyone gets is, even your dad ("yes, like Excel!"). However, I argue that it tends to restricts our vision of certain datasets, including tweets. Tables probably became popular, in part, because they not only structure data but also simplify it in some way. The simplification of the dataset subsequently simplifies their analysis.

Tweets, shouldn't be restricted to a table; it removes interesting and insightful complexity. Here is an example of tweet:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">ICYMI, 📊 Easy viz from <a href="https://twitter.com/hashtag/rtweet?src=hash&amp;ref_src=twsrc%5Etfw">#rtweet</a> data!<br>🐦 &quot;GraphTweets: Visualise Twitter Interactions&quot; ✩ <a href="https://twitter.com/jdatap?ref_src=twsrc%5Etfw">@jdatap</a><a href="https://t.co/SCN0Ycy7Z7">https://t.co/SCN0Ycy7Z7</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/9W4cNkEjf8">pic.twitter.com/9W4cNkEjf8</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1012380619425374210?ref_src=twsrc%5Etfw">June 28, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

[@dataandme](https://twitter.com/dataandme) tweets [@jdatap](https://twitter.com/jdatap). This should not be a single row of data isolated to my response to Mara's tweet. These should be looked at as connected data points; what better way than a network.

## Networks

The beauty of networks is that they do not remove complexity and their implicit insights, they instead map it. Thereby making sense of the complexity and _revealing_ insights.
